@url = http://localhost:3012

### get Api
{{url}}

### get Books
GET {{url}}/books

### get Book
GET {{url}}/books/63db20b61ac08343bded1dcb

### DeleteBook
DELETE {{url}}/books/63db20b61ac08343bded1dcb

### Add book
POST {{url}}/books
content-type: application/json

{
    "title": "The Age of American Unreason",
    "description": "Having grown up in America and having lived in Berlin, Germany for over two decades, I have noticed a rift between the two cultures in terms of the average level of *Bildung* (education and cultivation), and since I am raising two American/German children who are growing up in the German culture, I am reading this book to better understand the causes for the higher degree of anti-intellectualism, consumerism, scientific ignorance, and religious superstition that is found in American society.",
    "numberOfPages": 317,
    "language": "english",
    "imageUrl": "http://edwardtanguay.vercel.app/share/images/books/unreason.png",
    "buyUrl": "http://www.amazon.com/The-American-Unreason-Susan-Jacoby/dp/1400096383"
}

### EDIT BOOK
PUT {{url}}/books/63db20b61ac08343bded1dcb
content-type: application/json

{
    "title": "The Age of American Unreason",
    "description": "Having grown up in America and having lived in Berlin, Germany for over two decades, I have noticed a rift between the two cultures in terms of the average level of *Bildung* (education and cultivation), and since I am raising two American/German children who are growing up in the German culture, I am reading this book to better understand the causes for the higher degree of anti-intellectualism, consumerism, scientific ignorance, and religious superstition that is found in American society.",
    "numberOfPages": 317,
    "language": "english",
    "imageUrl": "http://edwardtanguay.vercel.app/share/images/books/unreason.png",
    "buyUrl": "http://www.amazon.com/The-American-Unreason-Susan-Jacoby/dp/1400096383"
}